--hl.config({
--	plugin = {
--		hyprexpo = {
--			columns = 3,
--			gaps_in = 5,
--			gaps_out = 0,
--			bg_col = "rgb(111111)",
--			workspace_method = "center current",
--			skip_empty = 1,
--			gesture_distance = 200,
--			cancel_key = "escape",
--			show_cursor = 0,
--		},
--	},
--})
