#############################
######## ANIMATIONS #########
#############################

animations {
    enabled = yes, porfa :)

    # --- Curvas Bezier ---
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = bouncy,         0.05, 0.9,  0.1,  1.05
    bezier = flash,          0.4,  0,    0.2,  1
    bezier = mapUnfold, 0.05, 0.9, 0.1, 1.05
    
    # --- Definición de Animaciones ---
    # Nombre, Activado(1/0), Velocidad, Curva, Estilo
    
    # Workspaces: Transición tipo flash y slidefade
    animation = workspaces, 1, 2.5, flash, slidefade 40%

    # Layers (Rofi, Waybar, Notificaciones)
    animation = layersIn, 1, 4, bouncy, slide top
    animation = layersOut, 1, 3, default, slide top

    # Windows (Apertura y Cierre)
    animation = windows, 1, 7, myBezier, slide bottom 10%
    animation = windowsOut, 1, 7, default, slide bottom 80%

    # Elementos UI (Bordes y Fade)
    animation = border, 1, 5.39, easeOutQuint
    animation = borderangle, 1, 15, default
    animation = fade, 1, 5, default
    animation = zoomFactor, 1, 7, quick
}
