######################
###### PLUGINS #######
######################

plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
	      skip_empty = true
        gesture_distance = 300 # how far is the "max" for the gesture
    }

    hyprtrails {
        color = rgba(ffaa00ff)
        bezier = myBezier, 0.05, 0.9, 0.1, 1.05 # Define una curva de salida
        points_per_step = 2 # Aumenta la densidad de la estela
        history_points = 20 # Longitud de la estela (puntos que deja atrás)
    }
}
