general {
    # Comando para bloquear (si ya se está ejecutando, no lanzar otro)
    lock_cmd = pidof hyprlock || hyprlock
    
    # Qué hacer antes de que el sistema se duerma (bloquear pantalla)
    before_sleep_cmd = loginctl lock-session
    
    # Qué hacer al despertar (encender pantalla)
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. A los 5 minutos (300s): Bloquear la pantalla
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 2. A los 5.5 minutos (330s): Apagar el monitor (ahorro de energía)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 3. A los 30 minutos (1800s): Suspender la laptop completamente
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
