general {
    # Comando de bloqueo invocando tu módulo de Quickshell
    lock_cmd = quickshell -c /home/taianlux/.config/quickshell/modules/lockscreen
    
    # Bloquea la sesión automáticamente antes de que el sistema se suspenda
    before_sleep_cmd = loginctl lock-session
    
    # Enciende las pantallas al volver del estado de suspensión
    after_sleep_cmd = hyprctl dispatch dpms on
}
# 1. Bloquear la pantalla a los 5 minutos de inactividad
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}
# 2. Apagar la pantalla (DPMS) a los 6 minutos
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
# 3. Suspender la laptop a los 10 minutos
listener {
    timeout = 600
    on-timeout = systemctl suspend
}

se debe hacer alguna adaptacion si estoy usando la nueva sintaxis de lua?
