#############################
#### GENERAL VARIABLES ######
#############################

# Definimos las variables globales aquí para que estén disponibles
# en todos los módulos (especialmente en keybinds.conf)
$terminal = kitty
$fileManager = nemo
$menu = rofi -show drun -theme ~/.config/rofi/style-7.rasi

#########################
####### MODULES #########
#########################

# Cargamos los módulos en orden lógico
# 1. Hardware y Entorno
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/env.conf

# 2. Inicio automático
source = ~/.config/hypr/modules/autostart.conf

# 3. Estética y Comportamiento
source = ~/.config/hypr/modules/general.conf
source = ~/.config/hypr/modules/animations.conf

# 4. Entrada y Atajos
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/keybinds.conf

# 5. Reglas y Plugins
source = ~/.config/hypr/modules/rules.conf
#source = ~/.config/hypr/modules/plugins.conf
