
#########################
####### AUTOSTART #######
#########################

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = nm-applet --indicator
exec-once = hyprpm reload -n
exec-once = hyprsunset
exec-once = swww-daemon
exec-once = waybar                                                      
exec-once = swayidle -w \
    before-sleep 'pgrep hyprlock || hyprlock'
exec-once = GSK_RENDERER=gl swayosd-server --top-margin 0.95
exec-once = clipse -listen 
#exec-once = swayosd-server --top-margin 0.95
exec-once = hyprctl setcursor Sunset-cursors 24
exec-once = blueman-applet
exec-once = kdeconnect-indicator
exec-once = hyprwave


