#############################
### GENERAL & DECORATION ####
#############################
source = ~/.config/hypr/colors.conf


general {
    gaps_in = 5
    gaps_out = 9
    border_size = 1
    
    # Colores de borde
    col.active_border = rgba(FFFFFF40)
    col.inactive_border = rgba(595959aa)
    
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5
}

workspace = 1, layout:scrolling
workspace = 2, layout:scrolling

bind = SUPER, period, layoutmsg, swapcol l
bind = SUPER, comma,  layoutmsg, swapcol r

decoration {
    rounding = 4
    rounding_power = 2
    active_opacity = 1.0 
    
    shadow {
        enabled = true
         range = 20
         render_power = 15
         color = rgba(0, 0, 0, 0.8)
         ignore_window = true
    }

    blur {
        popups = true  
        enabled = true
        new_optimizations = true
        size = 4
        passes = 4
        contrast = 1
        vibrancy = 0.2
        vibrancy_darkness = 0.2
        ignore_opacity = true
    }
}

#############################
########## LAYOUTS ##########
#############################

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

#############################
########### MISC ############
#############################

misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true
    vfr = true
}
