###############################
####### TECLADO Y RATÓN #######
###############################

input {
    kb_layout = latam
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 #Por defecto
    touchpad {
        natural_scroll = false
    }
}

device {
    name = logitech-g203-lightsync-gaming-mouse
    sensitivity = 0.6
}
