background #0f1512
foreground #dee4df

cursor #88d6bb
cursor_text_color #00382b

selection_foreground #a3f2d7
selection_background #00513f

active_border_color #88d6bb
inactive_border_color #3f4945

url_color #a8cbe2

macos_titlebar_color background

color0  #89938e
color8  #bfc9c3

color1  #a8cbe2
color9  #c4e7ff

color2  #88d6bb
color10 #a3f2d7

color3  #b2ccc1
color11 #cee9dd

color4  #88d6bb
color12 #a3f2d7

color5  #c4e7ff
color13 #a8cbe2

color6  #cee9dd
color14 #b2ccc1

color7  #bfc9c3
color15 #dee4df
