██╗░░██╗██╗████████╗████████╗██╗░░░██╗
██║░██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗░██╔╝
█████═╝░██║░░░██║░░░░░░██║░░░░╚████╔╝░
██╔═██╗░██║░░░██║░░░░░░██║░░░░░╚██╔╝░░
██║░╚██╗██║░░░██║░░░░░░██║░░░░░░██║░░░
╚═╝░░╚═╝╚═╝░░░╚═╝░░░░░░╚═╝░░░░░░╚═╝░░░


# -- Themes --

#include ~/.cache/wal/colors-kitty.conf 
include ~/.config/kitty/colors.conf


# -- Color Scheme --

background_opacity 0.65
background_blur 1
dynamic_background_opacity yes

# -- Font config --

#font_family      Hack Nerd Font Mono
#font_family       Pixel Operator Mono HB
#font_family      BigBlueTerm437 Nerd Font Mono
#font_family      BigBlueTermPlus Nerd Font Mono
#font_family      BigBlueTermPlus Nerd Font
#font_family Terminess Nerd Font Mono
#font_family ProggyClean Nerd Font Mono
#font_family  GohuFont uni14 Nerd Font
font_family  JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0


# -- Mics Settings --

enable_audio_bell no
force_ltr no
detect_urls yes
mouse_hide_wait -1
allow_remote_control yes
default_pointer_shape arrow
pointer_shape_when_grabbed arrow
placement_strategy center

# -- Window -- 

window_padding_width  0 5 5 5
remember_window_size  no
initial_window_width  1000
initial_window_height 550

# -- Tabs --

#active_tab_background   #7aa2f7
#active_tab_foreground   #1f2335
#inactive_tab_background #292e42
#inactive_tab_foreground #545c7e

cursor_trail 4
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 0

# -- Keybinds --
map ctrl+shift+alt+left resize_window narrower 1
map ctrl+shift+alt+right resize_window wider 1
map ctrl+shift+alt+up resize_window taller 1
map ctrl+shift+alt+down resize_window shorter 1
map rightctrl no_op
